before_script:
    - apt-get update -qq
    - apt-get upgrade -qy

build:
  script:
    - apt-get install -qy --fix-missing automake build-essential
      libevent-dev libssl-dev zlib1g-dev
      libseccomp-dev liblzma-dev libscrypt-dev
    - ./autogen.sh
    - ./configure --disable-asciidoc --enable-fatal-warnings
      --disable-silent-rules
    - make check || (e=$?; cat test-suite.log; exit $e)
    - make install

